### ISSUE TITLE
Casino dice added to photo at top of README.md

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/bc-lethe-kit#4]
@ksedgwic I'd love to see one or more casino dice along with the LetheKit box and dogtags in the photo at the top of the README.md. But only if it can look good as the one that you've already done ;-)

No urgency.

-- Christopher Allen

**Comment by ChristopherA** [comment]
I thought I merged a new photo, but it looks like the old photo without the dice.

**Comment by ksedgwic** [comment]
Looks good to me ... <SHIFT> - Reload?

**Comment by ChristopherA** [comment]
Yes, my browser was not clearing cache effectively. So this was fixed in #5 

Thank you!
